var AnnotationConstants = {
  ANNOTATIONS_FOR_SNIPPET_RECEIVED: "ANNOTATIONS_FOR_SNIPPET_RECEIVED",
  ANNOTATION_RECEIVED: "ANNOTATION_RECEIVED",
  ANNOTATION_REMOVED: "ANNOTATION_REMOVED"
};

module.exports = AnnotationConstants;
