var SnippetConstants = {
  SNIPPETS_ALL_RECEIVED: "SNIPPETS_ALL_RECEIVED",
  UNFETCHED_SNIPPETS_RECEIVED: "UNFETCHED_SNIPPETS_RECEIVED",
  SNIPPET_RECEIVED: "SNIPPET_RECEIVED",
  SNIPPET_REMOVED: "SNIPPET_REMOVED"
};

module.exports = SnippetConstants;
